### PR TITLE
586: dictionary word full

### LINKED ISSUE #586: Dictionary word layout full view
NOTE: there is a repeatable paragraph "word entry", and only the first is currently displaying.

Top
- Page title/dictionary word Term field
- Local task menu

Left
- Word entry 1 (this whole block repeats)
   - Alternate spelling
   - Translation
   - Recording
   - Definition
   - Sample sentences (mix of text and audio)
   - Word type
   - Pronunciation
   - Source
   - Word origin
   - Contributor
- Word entry 2 (etc)

Visual separator

- Media assets (not really sure about this placement)
- Map (does not need the "Location" label)
- Location
- Location description
- Citation (may not be added yet)

Right
- Community (can community/protocols be combined?)
- Cultual protocols
- Language
- Glossary entry (?)
- Keywords
- Thumbnail (maybe?)
- Word lists 
- Related content
- Local Contexts/TK Labels (may not be added yet)

V3 screenshot attached for reference 

Image

### PR DESCRIPTION
**Pull request by pjudge**
This PR closes #586

### CODE REVIEW

**Comment by pjudge** [comment]
@nick-deer @quicksketch This brings me to another thought -- how important is it to have the config separated by custom module? It would be much easier for me as a FE dev to have all the install config at the profile-level. Export/import by module is really complicated 😓

**Comment by nick-deer** [comment]
> @nick-deer @quicksketch
> 
> I'm getting this config error from Tugboat:
> 
> ```
> In PreExistingConfigException.php line 65:
>                                                                                
>   Configuration objects (field.storage.node.field_mukurtu_cluster_lat, field.  
>   storage.node.field_mukurtu_cluster_long, field.storage.node.field_mukurtu_g  
>   eojson) provided by mukurtu_browse already exist in active configuration     
>                                                                                
> ```
> 
> Looks like there's field config that's used by both the Mukurtu Browse and the Mukurtu Dictionary modules. I'm not sure why this is happening now... I had gotten an error about missing config (the ones listed above), so I added them to the module's config install. And now it's saying that the config already exists.
> 
> Any advice on how to solve this is appreciated!

Sorry for the confusion--those three fields (field_mukurtu_cluster_lat, field_mukurtu_cluster_long, field_mukurtu_geojson) are actually obsolete. Drupal keeps putting them in config exports for some reason. It should be safe to delete them. Apologies for the hassle!

**Comment by nick-deer** [comment]
> @nick-deer @quicksketch This brings me to another thought -- how important is it to have the config separated by custom module? It would be much easier for me as a FE dev to have all the install config at the profile-level. Export/import by module is really complicated 😓

Yeah I agree it's a headache for sure. It's a challenge because some config is essential for running Mukurtu (like for communities and protocols), and IMO should live at the profile level. However for other modules like the dictionary that aren't strictly required, we want people to have the option of uninstalling them, so the config in this case should exist at the module level. We are still discussing with @quicksketch to figure out which direction would be best.

**Comment by pjudge** [comment]
@michael-wynne-wsu I think this is ready for review. It looks like the patch that handles empty paragraphs didn't make it into the new composer.json, so for now ignore if you see empty paragraph labels rendering 👍

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr632-7ppcox3nwjj9dodk1zbam4yzpwhawpez.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673cfdf9513b09d01c324808

**Comment by michael-wynne-wsu** [comment]
@pjudge I haven't been able to confirm media display yet, but there are a few other changes needed:

- [ ] I thought we said "Other Entries" as the header after the core word. I'm not opposed t "Word Entries", but you weren't crazy about that label.
- [ ] Word entry "Terms" are not displaying (should be the first field, using the same red call-out as the main term.
- [ ] Word entry "alternate" spelling field is missing it's label.
- [ ] I think it would be nice to add an "additional information" or similar label after the entries/before the map etc.

Thanks!

Screenshot 2024-11-22 at 2 39 28 PM

Screenshot 2024-11-22 at 2 39 55 PM

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr632-7ppcox3nwjj9dodk1zbam4yzpwhawpez.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673cfdf9513b09d01c324808

**Comment by michael-wynne-wsu** [comment]
@pjudge same notes as above when I tested with GitPod just now. Additionally, the recording field isn't rendering the audio player (should include audio player + audio assets "contributor" field)

This-is-a-word-Mukurtu-CMS-11-25-2024_11_43_AM

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr632-7ppcox3nwjj9dodk1zbam4yzpwhawpez.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673cfdf9513b09d01c324808

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr632-7ppcox3nwjj9dodk1zbam4yzpwhawpez.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673cfdf9513b09d01c324808

**Comment by pjudge** [comment]
@michael-wynne-wsu @nick-deer This is ready for re-review!

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr632-7ppcox3nwjj9dodk1zbam4yzpwhawpez.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673cfdf9513b09d01c324808

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr632-7ppcox3nwjj9dodk1zbam4yzpwhawpez.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673cfdf9513b09d01c324808

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr632-7ppcox3nwjj9dodk1zbam4yzpwhawpez.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673cfdf9513b09d01c324808

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr632-7ppcox3nwjj9dodk1zbam4yzpwhawpez.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673cfdf9513b09d01c324808

**Review by nick-deer — APPROVED** [review]

**Comment by nick-deer** [comment]
@pjudge looks great but there are merge conflicts

**Pull request merged**
