### PR TITLE
Browse Pages

### PR DESCRIPTION
**Pull request by pjudge**
I think the following tickets could be closed with the merging of this PR:

- #283 
- #284 
- #239 
- #345 
- #208 
- #171 

This PR adds a lot! 
- Styles for /dictionary
- Styles and functionality for browse/browse dh -- including view switcher buttons (List, Grid, Map)
- first pass layout/style for dictionary word content type full display.

### CODE REVIEW

**Comment by michael-wynne-wsu** [comment]
@nick-deer I'm getting the attached error after saving or when trying to view a dictionary word.

Screenshot 2024-06-03 at 9 32 50 AM

**Comment by michael-wynne-wsu** [comment]
Same thing on DH pages.

Screenshot 2024-06-03 at 9 41 26 AM

**Comment by pjudge** [comment]
@michael-wynne-wsu @nick-deer It looks like the field group module just had a release to the dev version (which is what's specified in composer.json 😱 ) and that template got removed from the module https://git.drupalcode.org/project/field_group/-/commit/771352bf813a642383dcbcab320b8823a748bc43

I don't know if that's a mistake they're going to revert or what, but we should probably lock the field group version to a stable release. :D

**Comment by michael-wynne-wsu** [comment]
Thanks @pjudge and sorry, I didn't mean to ping you!

**Comment by nick-deer** [comment]
Alright @michael-wynne-wsu I got the field_group module to a stable release! Makes the errors go away on my end, let me know if that's true for you as well

**Comment by nick-deer** [comment]
@michael-wynne-wsu I merged the PR and have confirmed no more errors! Hope this is the case on your end too!

**Comment by michael-wynne-wsu** [comment]
Building and testing now - thank you for pushing this out today!

**Pull request merged**
