### PR TITLE
Loose ends

### PR DESCRIPTION
**Pull request by pjudge**
This PR is wrapping up some loose ends noted in our final meeting:

1. Removes thumbnail from sidebar of Dictionary word
2. Styles of all word entries in a dictionary word node (red background)
3. Spacing and dividers between fields on Dictionary word
4. Related content now showing on dictionary word
5. Only show parent collections in /collections
6. Side by side alignment of audio player and contributor for Recording on dictionary word

Notes:
* I am seeing this error on /dictionary:
`No available query types were found for facet Word Type`
I think the bug on this page may be a backend issue?

### CODE REVIEW

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr652-iyrfztrg58wtmjgqmtx2avr8ddqj6ll6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674e15dd036d6ee6a53f79d9

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr652-iyrfztrg58wtmjgqmtx2avr8ddqj6ll6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674e15dd036d6ee6a53f79d9

**Comment by pjudge** [comment]
Hi @michael-wynne-wsu @nick-deer This was as much as I could get to in the time I had! If there are any questions, I'll keep monitoring here. Thanks!!

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr652-iyrfztrg58wtmjgqmtx2avr8ddqj6ll6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674e15dd036d6ee6a53f79d9

**Comment by michael-wynne-wsu** [comment]
Thank you SO MUCH @pjudge this is all looking good on my end, and we really appreciate that extra time you took with us.

**Pull request merged**
