### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by michael-wynne-wsu**
Testing local editing.

Made a minor text edit to a readme file to test my setup. @nick-deer can you make sure that this seems like the proper workflow, valid PR etc? We can discuss before you accept it.

### CODE REVIEW

**Review by nick-deer — APPROVED** [review]
Looks good!

**Comment by michael-wynne-wsu** [comment]
@nick-deer looks like this build is failing checks and failing to build- not sure if it's related to what I pushed or not?

**Comment by michael-wynne-wsu** [comment]
Sounds good, maybe @jonscottwsu has an idea about the test suite?

There is one thing I want to confirm on this build before doing more - I haven't checked a ddev build yet though. Will do that now.

**Comment by michael-wynne-wsu** [comment]
@nick-deer @jonscottwsu It built fine in ddev. I was testing a minor edit to a field description in the hopes that I can start implementing things like that without troubling you and it seems to have worked, so that's excellent!

**Pull request merged**
