### PR TITLE
Global theming tweaks

### PR DESCRIPTION
**Pull request by pjudge**
This branch was named for the homepage tickets but actually ended up being used for some theming tweaks:

1. remove site name from under logo
2. continue styles for main navigation to get closer to v3; update templates.
3. Add mobile menu button for smaller screens. It currently "works" in that it goes to an active state when clicked, but the mobile navigation hasn't yet been styled.
4. Fix a JS bug regarding null values for the DH switcher
5. Add JS as libraries attached to twig templates. 
6. Added regions to the info file so they would appear in logical order in block layout page
7. Added styles for drupal messages

### CODE REVIEW

**Comment by michael-wynne-wsu** [comment]
@pjudge we're just deciding the best way for me to review - in the past we accepted Morgan's pulls and I reviewed with GitPod, but I might try to run with ddev or something this time. Sorry, we'll try to sort that out today!

**Comment by pjudge** [comment]
@michael-wynne-wsu No worries whatsoever!

**Comment by michael-wynne-wsu** [comment]
@pjudge for now @nick-deer will do a quick pass and then merge your branches so I can review via GitPod. So I'll drop comments after all that. Thanks for waiting!

**Comment by nick-deer** [comment]
Hi @pjudge I did an initial look over your changes and they seemed reasonable so I pulled them into main. Only thing is when I rebuilt the site fresh, I got this build error: 

`Configuration objects provided by <em class="placeholder">mukurtu</em> have unmet dependencies: <em class="placeholder">  
  block.block.mukurtu_v4_branding (mukurtu_v4)</em>`

**Comment by nick-deer** [comment]
Also @michael-wynne-wsu it doesn't look like I need to pull and merge the changes into main in order for you to see them in GitPod! I tried this the other day and now that I'm sure what I saw on my local dev instance is the same as in the pull request's GitPod instance, it looks like you can just hit the GitPod button on the pull request itself and see the changes.

**Comment by michael-wynne-wsu** [comment]
Yep, it's building for me now. However, with the Mukurtu theme enabled through gitpod, all I'm seeing is the Mukurtu logo, no menu (directly navigating to other pages is about the same. I'll try to pick it up in ddev on Monday, if no-one else is seeing this. @nick-deer @pjudge 

Screenshot 2024-04-05 at 3 16 40 PM

Screenshot 2024-04-05 at 3 17 39 PM

**Pull request merged**
