### PR TITLE
615: Set up Tugboat for Mukurtu.

### PR DESCRIPTION
**Pull request by quicksketch**
Fixes https://github.com/MukurtuCMS/Mukurtu-CMS/issues/615

### CODE REVIEW

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr616-ughd78derpbwxcbmblid51tpnf2y26aa.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672bbee0f95004fb1cc46679

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr616-ughd78derpbwxcbmblid51tpnf2y26aa.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672bbee0f95004fb1cc46679

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr616-ughd78derpbwxcbmblid51tpnf2y26aa.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672bbee0f95004fb1cc46679

**Comment by quicksketch** [comment]
This is now ready for review. Once merged, we can set up a base preview, that will speed up the performance of creating new previews substantially. We can talk about this during our sync tomorrow.

**Comment by nick-deer** [comment]
Wow, this spins up way faster than Gitpod! Happy to merge it

**Pull request merged**
