### PR TITLE
ensure paragraph types hide if empty

### LINKED ISSUE #663: Empty paragraphs patch is now broken/removed
@pjudge previously had a working patch to disable empty paragraphs from displaying. We think it got lost in the composer/config file reshuffle. Time-dependent, but maybe @quicksketch can help with it.

### PR DESCRIPTION
**Pull request by pjudge**
Closes #663 

To test, create a DH item and do not enter content in the indigenous knowledge keepers paragraph field. Save and note that there is no empty sidebar block.

Can also test with dictionary word nodes (leave paragraph field content empty, save, and view node).

### CODE REVIEW

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by pjudge** [comment]
@michael-wynne-wsu @quicksketch @nick-deer This PR provides the config necessary for the paragraphs patch to work (hiding empty paragraphs)

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
Thank you @pjudge - my apologies for adding this for you post-end date!

I'm testing it but @nick-deer this seems to have re-introduced sample sentence paragraphs as required (but also not able to be removed/still won't save even if populated)

Screenshot 2024-12-04 at 9 14 11 AM

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
@nick-deer I think you need to change sample sentences within the word entry paragraph to optional as well.

**Comment by nick-deer** [comment]
> @nick-deer I think you need to change sample sentences within the word entry paragraph to optional as well.

Good catch, thanks!

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr666-9ko7cnpv0zfcpwi6rhtha1lqwqsjtrvl.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674f8923aa4265bc09ea1985

**Comment by michael-wynne-wsu** [comment]
Excellent, sample sentences are no longer blocking word creation, but we're still got excess "other entries", "additional information" and map showing. 

I think this might have veered off this specific issue though. Unless you think otherwise I'll close this and log it separately.

Screenshot 2024-12-09 at 2 11 48 PM

**Comment by nick-deer** [comment]
> Excellent, sample sentences are no longer blocking word creation, but we're still got excess "other entries", "additional information" and map showing.
> 
> I think this might have veered off this specific issue though. Unless you think otherwise I'll close this and log it separately.
> 
> Screenshot 2024-12-09 at 2 11 48 PM

Yes, sounds good!

**Review by nick-deer — APPROVED** [review]

**Pull request merged**
