### PR TITLE
305: carousels final form

### PR DESCRIPTION
**Pull request by pjudge**
This PR provides a more finalized round of styles and function for synced carousels that appear when the media assets field on DH nodes has more than one item. This PR also adds some updated templates and config for display modes, specifically for when content appears on browse pages, below main content under related content, on sidebar under related content (though that is still WIP).

I believe this PR closes the following tickets:

- https://github.com/MukurtuCMS/Mukurtu-CMS/issues/305
- https://github.com/MukurtuCMS/Mukurtu-CMS/issues/308

### CODE REVIEW

**Comment by michael-wynne-wsu** [comment]
@pjudge One tiny note on the date, with "Month Day, Year" format, partial dates include spaces and comma as if the date was complete. But using both formats worked perfectly otherwise.

Screenshot 2024-05-02 at 1 19 06 PM

Screenshot 2024-05-02 at 1 19 52 PM

**Comment by nick-deer** [comment]
@michael-wynne-wsu Regarding the partial date display, I think that's an issue with the formatters I worked on not accounting for partial dates. I can change that!

**Comment by michael-wynne-wsu** [comment]
I made some kind of cursed carousels and am going to break out independent issues for each different component. Overall this is working really well, just have some questions and a couple notes. Potentially we could move some of these to lower priority if you feel the need to move on to something else, because it's very functional, mostly looking at minor adjustments (I think).

https://github.com/MukurtuCMS/Mukurtu-CMS/issues/308 (this isn't really the focus of this PR, just flagging it since I noticed while testing CR tabs + media assets carousel, but it's the same regardless of how many media assets)

https://github.com/MukurtuCMS/Mukurtu-CMS/issues/328 (the default graphics from v3 are ugly)

https://github.com/MukurtuCMS/Mukurtu-CMS/issues/329 (applies to carousel as well as single media)

https://github.com/MukurtuCMS/Mukurtu-CMS/issues/330 and https://github.com/MukurtuCMS/Mukurtu-CMS/issues/331 (one is about media and one is about multipage item but the points are basically the same).

**Comment by michael-wynne-wsu** [comment]
> @michael-wynne-wsu Regarding the partial date display, I think that's an issue with the formatters I worked on not accounting for partial dates. I can change that!

@nick-deer great I'll move my comments into the other date format issue.

**Comment by nick-deer** [comment]
@pjudge I think this looks great regarding our requirements! I do agree with Michael's comments, but I will merge this PR as the base functionality is there.

**Comment by michael-wynne-wsu** [comment]
Yes, thank you Nick!

**Pull request merged**
