### PR TITLE
Remove slick and its dependencies; styles carousels

### PR DESCRIPTION
**Pull request by pjudge**
This PR encompasses a few things:

- it removes the slick module and related libraries, in favor of Splide (which was already installed)
- it creates a Splide library inside the theme so it can be easily accessed by theme or modules
- adds a Media Assets display mode for all media types, to display the media assets field correctly on DH nodes
- adds styles and functionality for Multi-page carousel
- adds styles and functionality for media assets carousel (though a bug remains on pages that have both the multipage carousel and the media assets carousel)
- config and styles for embedded media including user friendly names for image styles and minor styling for captions
- initial style idea for local contexts info in the DH sidebar
- fix ajax bug for anons

I think with this PR, the following tickets can be closed:

- #311 
- #280 
- #278 
- #138 
- #85

### CODE REVIEW

**Comment by nick-deer** [comment]
@pjudge I spun up a Gitpod instance of this to investigate why Blazy is not being enabled, and the build failed with this message: `Configuration objects provided by <em class="placeholder">mukurtu_dictionary</em> have unmet dependencies: <em class="placeholder">core.entity_view_display.node.dictionary_word.content_browser (blazy)</em>`. I see that `mukurtu_dictionary.info.yml` doesn't have Blazy listed in the dependencies, maybe that's why Blazy isn't showing as enabled? I'm not sure though, until I can get a working build I can't verify if Blazy is enabled. Are you getting this error on your end too? I'm baffled why it's here to be honest--many of our view displays had Blazy as a dependency prior to the changes in your PR here, and they never complained about it, despite Blazy not being officially enabled in the install profile...

**Comment by pjudge** [comment]
@nick-deer Yeah, that's the error I'm trying to debug, and my guess is that it's happening because Blazy isn't being enabled, after removing Slick. 

If you start a gitpod instance from this PR, or my branch, you can `cd` into `web/profiles/mukurtu-cms`.

From there you can `ddev drush cex` to look at `core.extension.yml` and see that Blazy isn't installed. 
Or you can run `ddev drush uli` to log in. (The themes aren't loading but the site is functional.)

**Comment by pjudge** [comment]
Screenshot 2024-04-19 at 3 50 23 PM

**Comment by nick-deer** [comment]
@pjudge I figured out how to resolve the error! Just add blazy as a dependency to `mukurtu_dictionary.info.yml`!

**Comment by pjudge** [comment]
@nick-deer ah, of course! thanks, i'll try that.

**Comment by nick-deer** [comment]
@pjudge It looks awesome, thank you so much! There was only one thing I noticed: I made a DH item with one external embed media item and made it a page in a multipage item. For some reason, the external embed was showing up twice: 
image
This may be related to the bug you mentioned about when an item has both a media assets carousel and a multipage item carousel, but I'm not exactly sure. Otherwise, looks great! I'll wait for everyone else to comment stuff in case I missed something.

**Comment by michael-wynne-wsu** [comment]
@nick-deer It looks like multiple media files are showing in your MPI carousel, that is not what I'm getting. Did you build that from this pull request or main?

What I'm seeing/attaching is what I would expect. In the MPI carousel (the first one) there is a thumbnail of the first/only media asset within the selected page. Then in the media assets field you see that thumbnail again. 

Screenshot 2024-04-26 at 2 50 12 PM

One thing I just noticed is that when I have the same setup as above (a MPI with a DH item page within that has multiple media assets), it loads fine initially, then I move to another page, fine, then I move BACK to the first page and my multiple media asset carousel is no longer displaying.

Screenshot 2024-04-26 at 2 52 57 PM

Screenshot 2024-04-26 at 2 53 04 PM

Screenshot 2024-04-26 at 2 53 09 PM

**Comment by nick-deer** [comment]
@michael-wynne-wsu Oh I see, those are two carousels on top of each other, never mind then! Works as expected.

**Comment by pjudge** [comment]
@michael-wynne-wsu @nick-deer did anyone want to do more testing before i merge?

**Comment by michael-wynne-wsu** [comment]
@pjudge I'm happy for you to merge it!

**Pull request merged**
