### PR TITLE
Dictionary word changes

### PR DESCRIPTION
**Pull request by nick-deer**
Here's a first pass on changes to dictionary word and dictionary word entry! 

Changes:
- Factored Alternate Spelling field out of Word Entry and added it to Dictionary Word. 
- Added two new Dictionary Word fields: Base Word Entry (required, single value) and Additional Word Entries (optional, multi-value). These new fields also have their own tabs in the form display. 
- Added new Word Entry Term field to word entries

@michael-wynne-wsu let me know what you think! Totally welcome to changes, this is only a draft

### CODE REVIEW

**Comment by michael-wynne-wsu** [comment]
@nick-deer great, two notes so far:
1) "alternate spelling" should still be present in "additional word entry" paragraph.
2) I would like to merge "mukurtu essentials" and "base word entry" into one tab. Any objections to that? If not, I think I want to rearrange fields/tabs in some other ways too - I can lay out what I have in mind and you can weigh in?

**Comment by nick-deer** [comment]
@michael-wynne-wsu no objections from me, I can merge those tabs

**Comment by nick-deer** [comment]
@michael-wynne-wsu to clarify, you wanted the alternate spelling field on dictionary word AND additional word entry?

**Comment by michael-wynne-wsu** [comment]
@nick-deer I just wrote it up in a dedicated issue so we don't lose the conversation: https://github.com/MukurtuCMS/Mukurtu-CMS/issues/260

Do you want more context/justification for this grouping and ordering?

**Comment by nick-deer** [comment]
@michael-wynne-wsu thanks for linking that issue! It answers all my questions for now

**Comment by nick-deer** [comment]
@michael-wynne-wsu I realized an issue. The base word entry's title is supposed to be 'Term', but the additional word entries are supposed to have the title 'word entry term'. However, I cannot declare a base field to have two different names. 

I think the least gross solution would be to keep using the current v4 word entry paragraph, but abstract its title to 'Term' and use two different fields for word entries--base and additional. Requires only trivial changes to word entry base fields, and there's still visual distinction from the base word entry vs. additional ones.

Let me know what you think, down to talk about this more during the meeting!

**Comment by michael-wynne-wsu** [comment]
@nick-deer I think I need to see that in front of me - let's chat in meeting.

**Comment by nick-deer** [comment]
@michael-wynne-wsu changes are here! I notice the checks are failing and it's something Tugboat-related--the build itself is fine

**Comment by michael-wynne-wsu** [comment]
@nick-deer I will confirm soon, just heading away for lunch.

**Comment by michael-wynne-wsu** [comment]
@nick-deer Yes, that is spot on!

One note, the recording field in the first tab is a different widget than the others. Update that and then I think it's good to merge.

Screenshot 2024-11-06 at 12 50 12 PM

**Comment by michael-wynne-wsu** [comment]
@nick-deer Could you also move "keywords" from "additional fields" to the "Mukurtu essentials" tab? It does NOT need to be included in the word entries paragraph

**Comment by michael-wynne-wsu** [comment]
@nick-deer this looks good to me

**Comment by nick-deer** [comment]
@michael-wynne-wsu made those changes! Let me know if you have a preference on field ordering for the LC fields

**Comment by michael-wynne-wsu** [comment]
@nick-deer the way they are is good. Happy for you to merge this whenever you're ready!

**Comment by nick-deer** [comment]
@michael-wynne-wsu realized I need to re-index dictionary search fields and change the dictionary migration tools--I'll do that and then merge this

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr606-soomppgqtsemyu1hm39a3qymbkub8myj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e5acd21db79eb2378f738

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr606-soomppgqtsemyu1hm39a3qymbkub8myj.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e5acd21db79eb2378f738

**Pull request merged**
