### PR TITLE
351: digital heritage browse

### PR DESCRIPTION
**Pull request by pjudge**
This PR addresses the first 7 checkboxes of #351

### CODE REVIEW

**Comment by pjudge** [comment]
@michael-wynne-wsu If you have a chance to test this as-is, let me know! It's already got a bunch of work on this branch, I wouldn't mind splitting #351 into more than 1 PR

**Comment by michael-wynne-wsu** [comment]
@pjudge after my next meeting I'll get on this. And agree that it should be multiple PRs.

**Comment by michael-wynne-wsu** [comment]
@pjudge a few notes (everything else is good in my testing)

1) Could the "reset" button be available when facets are applied WITHOUT any search box input? Otherwise a user would need to uncheck all selections or use a normal browser reload.
Screenshot 2024-11-06 at 11 03 07 AM

2) I noticed this when I first loaded up the browse page but it doesn't seem to persist/recur. Not sure if it's worth exploring without more conclusive testing, but wanted to flag it just in case.
Screenshot 2024-11-06 at 10 54 54 AM

3) In grid view, external embed is showing both the thumbnail and embed.
Screenshot 2024-11-06 at 10 58 17 AM


I spotted a few other things not directly in this PR, will give them new issues.

**Comment by pjudge** [comment]
@michael-wynne-wsu Thanks for those catches! I'll work on them this morning. I'm not sure about the reset button -- I'll if it's possible.

**Comment by michael-wynne-wsu** [comment]
@pjudge Would it make sense for that button to just reload the page? Since that has the same effect.

**Comment by pjudge** [comment]
@michael-wynne-wsu As far as the functionality of the facets -- it's a bit outside of my wheelhouse. I believe they are set to "OR" but sometimes what's showing up for me, based on the facets I've checked, isn't what I expected. I can look more deeply or if a backend developer has more experience with facets than I do, they are more than welcome.

**Comment by michael-wynne-wsu** [comment]
@pjudge Don't worry about the facet functionality - I've got that logged here for something for us to confirm on the backend: https://github.com/MukurtuCMS/Mukurtu-CMS/issues/619 

And I'm just building a site to test the updates now

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr612-2czxzxjb82o49utmaddjjuprlyxznxno.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672e558721db79eb23785bb6

**Comment by michael-wynne-wsu** [comment]
@pjudge external embed on grid is sorted and the reset/reset filters buttons work well for me. I think It's ready to merge unless there is more you have coming on this PR.

**Comment by michael-wynne-wsu** [comment]
@nick-deer please merge when you're able

**Pull request merged**
