### PR TITLE
Update mukurtu_collection.routing.yml

### PR DESCRIPTION
**Pull request by michael-wynne-wsu**
Setting sub-collection create page to use admin form theme.

### CODE REVIEW

**Comment by michael-wynne-wsu** [comment]
@quicksketch this isn't higher priority than your current stuff, but if you have any idea why this is failing I would appreciate it!

I even undid the one line change I made and it's still failing on tugboat.

**Comment by quicksketch** [comment]
@michael-wynne-wsu Everything apparently was fine! The branch was just out-of-date. I merged in `main` and now it's passing Tugboat correctly.

There's a feature you can enable in GitHub that shows a button to update a PR if it's out-of-date. It's just under the first tab of the Repository settings ("General") about half-way down:

image

Turning that on might help make it more noticeable when a PR needs to be caught-up with `main`.

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr651-mcnhwfhopbsa4npzl3v0hxxhohzajajr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674e067eb8d4abaca99dc92f

**Comment by michael-wynne-wsu** [comment]
@quicksketch that's my git naivete showing, thank you for helping! And I've enabled that setting.

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr651-mcnhwfhopbsa4npzl3v0hxxhohzajajr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674e067eb8d4abaca99dc92f

**Comment by michael-wynne-wsu** [comment]
@jonscottwsu @nick-deer I've confirmed that the functionality I changed is working, and everything looks good but if either of you can review and merge that would be great!

**Review by nick-deer — APPROVED** [review]

**Pull request merged**
