### PR TITLE
Update mukurtu_core.links.menu.yml

### PR DESCRIPTION
**Pull request by michael-wynne-wsu**
Adding the "add content" link to the user account menu. Still need to figure out how to make it an expanded dropdown - probably in theming somewhere.

### CODE REVIEW

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr646-o8r1rugm4zeozbgiptftgb1odevmrw61.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67477b61d871e5f07412eafb

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr646-o8r1rugm4zeozbgiptftgb1odevmrw61.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67477b61d871e5f07412eafb

**Comment by michael-wynne-wsu** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr646-o8r1rugm4zeozbgiptftgb1odevmrw61.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/67477b61d871e5f07412eafb

**Comment by michael-wynne-wsu** [comment]
@nick-deer or @jonscottwsu can you review when you have time?

**Review by nick-deer — APPROVED** [review]
Looks great!

**Pull request merged**
