### PR TITLE
600: display local contexts in two columns in sidebar

### LINKED ISSUE #600: Basic Local Contexts Labels display
There will be a separate issue for full functionality. See #601 if interested.

DH items will likely display multiple TK/BC Labels and/or Notices. For now, maybe...

- [ ] Reduce size of icons. 
- [ ] 2 column for space efficiency?

For a quick test, at /dashboard/local-contexts/projects/site/add use this project ID 50b3ffe4-f641-4e5c-960f-11220aa743c9
Then in any DH item, select "my first project" in the relevant section.

Real v3 example: https://passamaquoddypeople.com/digital-heritage/esunomawotultine

Image

### PR DESCRIPTION
**Pull request by pjudge**
Closes #600 

This PR adds styling to display local contexts in the sidebar of DH nodes in a two-column format.

### CODE REVIEW

**Comment by pjudge** [comment]
@michael-wynne-wsu There are TK labels and BC labels and it looks like they're rendered one after the other, but inside different HTML elements. See screenshot:

Screenshot 2024-10-30 at 10 24 15 AM

So it almost appears as if the BC label is just hanging out by itself. Is this ok?

**Comment by pjudge** [comment]
@nick-deer I've fixed the merge conflict, this should be ready for review. Thanks!

**Comment by michael-wynne-wsu** [comment]
@nick-deer @pjudge I am still getting Gitpod build errors unfortunately.

Is it building locally for you both?

**Comment by nick-deer** [comment]
@michael-wynne-wsu I just merged a PR of Pauline's that fixes the gitpod errors, let me know if you see it working too!

**Comment by nick-deer** [comment]
@michael-wynne-wsu no, it was this one: https://github.com/MukurtuCMS/Mukurtu-CMS/pull/605. I merged that one to main and confirmed gitpod was working there. This PR's gitpod still errors out

**Comment by pjudge** [comment]
@michael-wynne-wsu @nick-deer I just updated this branch with main. This should fix the gitpod.

**Comment by michael-wynne-wsu** [comment]
Oh fantastic. It is displaying columned, but my view is a bit different than what you shared earlier. @pjudge 

Screenshot 2024-10-31 at 10 55 23 AM

**Pull request merged**
